// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// sessionからuserIdを取る
type Bot struct {
	IncludeBot bool `json:"includeBot"`
}

// sessionからuserIdを取る
type Me struct {
	IncludeMe bool `json:"includeMe"`
}

// RecommendedWord defines model for RecommendedWord.
type RecommendedWord struct {
	Number int    `json:"number"`
	Word   string `json:"word"`
}

// RecommendedWords defines model for RecommendedWords.
type RecommendedWords = []RecommendedWord

// SimilarUser defines model for SimilarUser.
type SimilarUser struct {
	UserId string `json:"userId"`
}

// SimilarUsers defines model for SimilarUsers.
type SimilarUsers = []SimilarUser

// TrendingWord defines model for TrendingWord.
type TrendingWord struct {
	Number int    `json:"number"`
	Word   string `json:"word"`
}

// TrendingWords defines model for TrendingWords.
type TrendingWords = []TrendingWord

// UserListItem defines model for UserListItem.
type UserListItem struct {
	IncludeBot bool      `json:"includeBot"`
	IncludeMe  bool      `json:"includeMe"`
	Time       time.Time `json:"time"`
	UserId     string    `json:"userId"`
}

// UsersList defines model for UsersList.
type UsersList = []UserListItem

// UsersOfWordListItem defines model for UsersOfWordListItem.
type UsersOfWordListItem struct {
	UserIds []UserListItem `json:"userIds"`
	Word    string         `json:"word"`
}

// UsersOfWordsList defines model for UsersOfWordsList.
type UsersOfWordsList = []UsersOfWordListItem

// WordAllListItem defines model for WordAllListItem.
type WordAllListItem struct {
	IncludeBot bool      `json:"includeBot"`
	IncludeMe  bool      `json:"includeMe"`
	Time       time.Time `json:"time"`
	UserId     string    `json:"userId"`
	Word       string    `json:"word"`
}

// sessionからuserIdを取る
type WordBotSetting struct {
	IncludeBot bool   `json:"includeBot"`
	Word       string `json:"word"`
}

// sessionからuserIdを取る
type WordDelete struct {
	Word string `json:"word"`
}

// WordListItem defines model for WordListItem.
type WordListItem struct {
	IncludeBot bool      `json:"includeBot"`
	IncludeMe  bool      `json:"includeMe"`
	Time       time.Time `json:"time"`
	Word       string    `json:"word"`
}

// sessionからuserIdを取る
type WordMeSetting struct {
	IncludeMe bool   `json:"includeMe"`
	Word      string `json:"word"`
}

// sessionからuserIdを取る
type WordRequest struct {
	IncludeBot bool   `json:"includeBot"`
	IncludeMe  bool   `json:"includeMe"`
	Word       string `json:"word"`
}

// WordsAllList defines model for WordsAllList.
type WordsAllList = []WordAllListItem

// WordsList defines model for WordsList.
type WordsList = []WordListItem

// WordsOfUserListItem defines model for WordsOfUserListItem.
type WordsOfUserListItem struct {
	UserId string         `json:"userId"`
	Words  []WordListItem `json:"words"`
}

// WordsOfUsersList defines model for WordsOfUsersList.
type WordsOfUsersList = []WordsOfUserListItem

// GetTodayTrendingWordsParams defines parameters for GetTodayTrendingWords.
type GetTodayTrendingWordsParams struct {
	// 返すwordの数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTrendingWordsForDayParams defines parameters for GetTrendingWordsForDay.
type GetTrendingWordsForDayParams struct {
	// 返すwordの数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTrendingWordsForMonthParams defines parameters for GetTrendingWordsForMonth.
type GetTrendingWordsForMonthParams struct {
	// 返すwordの数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTrendingWordsForYearParams defines parameters for GetTrendingWordsForYear.
type GetTrendingWordsForYearParams struct {
	// 返すwordの数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteWordsJSONBody defines parameters for DeleteWords.
type DeleteWordsJSONBody = WordDelete

// PostWordsJSONBody defines parameters for PostWords.
type PostWordsJSONBody = WordRequest

// PutWordsJSONBody defines parameters for PutWords.
type PutWordsJSONBody = WordBotSetting

// PostWordsBotJSONBody defines parameters for PostWordsBot.
type PostWordsBotJSONBody = Bot

// PutWordsMeJSONBody defines parameters for PutWordsMe.
type PutWordsMeJSONBody = WordMeSetting

// PostWordsMeAllJSONBody defines parameters for PostWordsMeAll.
type PostWordsMeAllJSONBody = Me

// DeleteWordsJSONRequestBody defines body for DeleteWords for application/json ContentType.
type DeleteWordsJSONRequestBody = DeleteWordsJSONBody

// PostWordsJSONRequestBody defines body for PostWords for application/json ContentType.
type PostWordsJSONRequestBody = PostWordsJSONBody

// PutWordsJSONRequestBody defines body for PutWords for application/json ContentType.
type PutWordsJSONRequestBody = PutWordsJSONBody

// PostWordsBotJSONRequestBody defines body for PostWordsBot for application/json ContentType.
type PostWordsBotJSONRequestBody = PostWordsBotJSONBody

// PutWordsMeJSONRequestBody defines body for PutWordsMe for application/json ContentType.
type PutWordsMeJSONRequestBody = PutWordsMeJSONBody

// PostWordsMeAllJSONRequestBody defines body for PostWordsMeAll for application/json ContentType.
type PostWordsMeAllJSONRequestBody = PostWordsMeAllJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// あるuserのwordたち
	// (GET /list/user/{userId})
	GetListUserUserId(ctx echo.Context, userId string) error
	// あるuserのwordたちを登録しているuserたち
	// (GET /list/user/{userId}/users)
	GetListUserUserIdUsers(ctx echo.Context, userId string) error
	// ある単語を見ているuserたち
	// (GET /list/word/{word})
	GetListWordWord(ctx echo.Context, word string) error
	// あるwordのuserたちが登録しているwordたち
	// (GET /list/word/{word}/words)
	GetListWordWordWords(ctx echo.Context, word string) error
	// 似たような者を探す
	// (GET /similar/{userId})
	GetUsersWithSimilarWords(ctx echo.Context, userId string) error
	// おすすめの単語を出す
	// (GET /similar/{userId}/recommend)
	GetRecommendedWordsForUser(ctx echo.Context, userId string) error
	// 今日のトレンド
	// (GET /trend/day/today)
	GetTodayTrendingWords(ctx echo.Context, params GetTodayTrendingWordsParams) error
	// ある日のトレンド
	// (GET /trend/day/{day})
	GetTrendingWordsForDay(ctx echo.Context, day string, params GetTrendingWordsForDayParams) error
	// ある月のトレンド
	// (GET /trend/month/{month})
	GetTrendingWordsForMonth(ctx echo.Context, month string, params GetTrendingWordsForMonthParams) error
	// ある年のトレンド
	// (GET /trend/year/{year})
	GetTrendingWordsForYear(ctx echo.Context, year string, params GetTrendingWordsForYearParams) error
	// wordの削除
	// (DELETE /words)
	DeleteWords(ctx echo.Context) error
	// 全データの取得
	// (GET /words)
	GetWords(ctx echo.Context) error
	// wordの登録
	// (POST /words)
	PostWords(ctx echo.Context) error
	// bot投稿に対する通知の設定
	// (PUT /words)
	PutWords(ctx echo.Context) error
	// bot投稿に対する通知の一括設定error
	// (POST /words/bot)
	PostWordsBot(ctx echo.Context) error
	// 自分の投稿に対する通知の設定
	// (PUT /words/me/)
	PutWordsMe(ctx echo.Context) error
	// 自分の投稿に対する通知の一括設定
	// (POST /words/me/all)
	PostWordsMeAll(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetListUserUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetListUserUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetListUserUserId(ctx, userId)
	return err
}

// GetListUserUserIdUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetListUserUserIdUsers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetListUserUserIdUsers(ctx, userId)
	return err
}

// GetListWordWord converts echo context to params.
func (w *ServerInterfaceWrapper) GetListWordWord(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "word" -------------
	var word string

	err = runtime.BindStyledParameterWithLocation("simple", false, "word", runtime.ParamLocationPath, ctx.Param("word"), &word)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter word: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetListWordWord(ctx, word)
	return err
}

// GetListWordWordWords converts echo context to params.
func (w *ServerInterfaceWrapper) GetListWordWordWords(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "word" -------------
	var word string

	err = runtime.BindStyledParameterWithLocation("simple", false, "word", runtime.ParamLocationPath, ctx.Param("word"), &word)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter word: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetListWordWordWords(ctx, word)
	return err
}

// GetUsersWithSimilarWords converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersWithSimilarWords(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUsersWithSimilarWords(ctx, userId)
	return err
}

// GetRecommendedWordsForUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetRecommendedWordsForUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRecommendedWordsForUser(ctx, userId)
	return err
}

// GetTodayTrendingWords converts echo context to params.
func (w *ServerInterfaceWrapper) GetTodayTrendingWords(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTodayTrendingWordsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTodayTrendingWords(ctx, params)
	return err
}

// GetTrendingWordsForDay converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrendingWordsForDay(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "day" -------------
	var day string

	err = runtime.BindStyledParameterWithLocation("simple", false, "day", runtime.ParamLocationPath, ctx.Param("day"), &day)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter day: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrendingWordsForDayParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTrendingWordsForDay(ctx, day, params)
	return err
}

// GetTrendingWordsForMonth converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrendingWordsForMonth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "month" -------------
	var month string

	err = runtime.BindStyledParameterWithLocation("simple", false, "month", runtime.ParamLocationPath, ctx.Param("month"), &month)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrendingWordsForMonthParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTrendingWordsForMonth(ctx, month, params)
	return err
}

// GetTrendingWordsForYear converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrendingWordsForYear(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "year" -------------
	var year string

	err = runtime.BindStyledParameterWithLocation("simple", false, "year", runtime.ParamLocationPath, ctx.Param("year"), &year)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter year: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrendingWordsForYearParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTrendingWordsForYear(ctx, year, params)
	return err
}

// DeleteWords converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWords(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteWords(ctx)
	return err
}

// GetWords converts echo context to params.
func (w *ServerInterfaceWrapper) GetWords(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWords(ctx)
	return err
}

// PostWords converts echo context to params.
func (w *ServerInterfaceWrapper) PostWords(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostWords(ctx)
	return err
}

// PutWords converts echo context to params.
func (w *ServerInterfaceWrapper) PutWords(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutWords(ctx)
	return err
}

// PostWordsBot converts echo context to params.
func (w *ServerInterfaceWrapper) PostWordsBot(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostWordsBot(ctx)
	return err
}

// PutWordsMe converts echo context to params.
func (w *ServerInterfaceWrapper) PutWordsMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutWordsMe(ctx)
	return err
}

// PostWordsMeAll converts echo context to params.
func (w *ServerInterfaceWrapper) PostWordsMeAll(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostWordsMeAll(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/list/user/:userId", wrapper.GetListUserUserId)
	router.GET(baseURL+"/list/user/:userId/users", wrapper.GetListUserUserIdUsers)
	router.GET(baseURL+"/list/word/:word", wrapper.GetListWordWord)
	router.GET(baseURL+"/list/word/:word/words", wrapper.GetListWordWordWords)
	router.GET(baseURL+"/similar/:userId", wrapper.GetUsersWithSimilarWords)
	router.GET(baseURL+"/similar/:userId/recommend", wrapper.GetRecommendedWordsForUser)
	router.GET(baseURL+"/trend/day/today", wrapper.GetTodayTrendingWords)
	router.GET(baseURL+"/trend/day/:day", wrapper.GetTrendingWordsForDay)
	router.GET(baseURL+"/trend/month/:month", wrapper.GetTrendingWordsForMonth)
	router.GET(baseURL+"/trend/year/:year", wrapper.GetTrendingWordsForYear)
	router.DELETE(baseURL+"/words", wrapper.DeleteWords)
	router.GET(baseURL+"/words", wrapper.GetWords)
	router.POST(baseURL+"/words", wrapper.PostWords)
	router.PUT(baseURL+"/words", wrapper.PutWords)
	router.POST(baseURL+"/words/bot", wrapper.PostWordsBot)
	router.PUT(baseURL+"/words/me/", wrapper.PutWordsMe)
	router.POST(baseURL+"/words/me/all", wrapper.PostWordsMeAll)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/jxhH+K8K2QL/ojr5c+kXfzjBSGK1wQezAMBKjoMWVxYDk8naXbgVDgEknd7bl",
	"NsGll4uvaZwWiWvcpeo7ECfX+MesZcv/opglKZEiKVK2VLvBfbHeuLMzz/PM7O6sN1CNmDaxsMUZqmwg",
	"VmtgU5VvZwmHFw2zGtVtrhMLVRDDjOnEEm5beDsOw3ReE97j7oefCK+NysimxMaU61ha0K2a4Wg4MIR/",
	"rZq2gVGFUweXEW/aGFXQKiEGVi3UapURxQ8cnWINVd6Jjl3pP0xW38M1jlplVMWT8c23cynXqjjVs7dw",
	"jZgmtjSsLRGqgfn4zJZjrmIam/ZO345ucbyGKRj6VTC6/1T/Xf9pxqlurSUcDGYITBRw0keEY1O++THF",
	"dVRBP1IG0lACXSjD0bX6xlVK1SZ8XtBN3VDp28wPMh68T0s8LE5VOzemYGBaMJEJiwcS9TIliEWKLU23",
	"1m4uhVEPi4cdiyslbsDjFzrj8xybybjjCT2cJuV4UiV/5ropf6kTaqocVZCmcnxLfpvAo3xlqQTzlaNe",
	"l3OSV2oI4i8MaAywDEDZ/TrgnY2r7zGb2KSh7orgxEaJLOL9+LAMh53iKPx+zzD+7xQ3HsQhwpdRJCA0",
	"S/gC5hwmmOSCnISrWFBBLDkrNDg+hw3Mr7pSj+FUlh83RF9jwXs5qVTxRJWSFfdlhDLC67fwAwczPmV1",
	"TyGmorSwoMgVrp/DhTGjdrKxjeZavF8fvQcYt0iyCbmXwgMsXSP2hZFwxsdpGIekP1JRdZIU7eLsnMxf",
	"LrFpvHaX/fLOT3/CSgzTdb0GSb2OKfOfvXN75vYMGCc2tlRbRxV09/bM7bsgbpU3pKuKoTOuQKDKhh9u",
	"C75ewykJA78Lt3O+/93F3j+E+1S4h8J9X3htwEu4ne6Hn3S/f4rkfFSFQcAl+hnmEClE/Ha4ZNkqVU3M",
	"5ab6neF55udKpF7iDVyCGWUOoIp0GZWRpUJVHCx+A97885WPc1qurcDDzCYW88X22swMvNSIxbElw1Vt",
	"29Br0nPlPQa+bETs5bIqdSC5i8ez4NRqmLG6Y5Qo5lTH66oBtLw+83oSZICoZBFeqhPH0qQ0mWOaKm2i",
	"ChKuJ7x2wIOP+oFw/wiKUNcASgR0ohUYlcKs/MQy+Y1a30uyLNx94R7Lj8HcHeH+QXh7wv0c/nqPk2Pk",
	"hGNIwz9n/fD0kdjrXodMMhnKVRHYUDbgbytHPd3ffNp7/vmImXKkAAgt+cvgSA0sNnAJ/ClxUmJYpbVG",
	"qU4ytBAsqzdICRORAMCUI4E+G73D9qUZV/or7QjepcrSWI9WjUABsaqRVmnkhIWlshSs1j9MvSQ2Gv8D",
	"2QTVfSCUTJZG6Yj5XbD8fcX5znG386w/4VH3oz3hfiq8beE+FO7zq5QUCduSzhtBSy7UytToivULU6i6",
	"//MhxE9fvgQQw2B7mx8I7/HZb/8k3P0IrAGWaKV1TWtjGqEKDRu2U6M2RXbBmFGsD3eg3yB+L3aKvCea",
	"3kW4F+6uLI/7wnMhoBCN7qNvbyD9nGJLUzS1qXCiqc1Mzk+/2z17+tXZZ5vC83on/+nufiHcJ7LUH+Qe",
	"FBbBcrz7nBNx7+R3wt0PDJ89+VsY8wMH0+YgaEM3dThOD2LUcF11DI4qd2aS7fWplvR4fIWKhIQUls6t",
	"bbH1tdj6p9jaiehDUhOU3QFNG5raLFB1peUXl+QrGsobhM6pzVeE9dfRQpzlwLVg45pe12slTW2WdEvm",
	"tt8RLL2LlpeXl29Vq7fm5t5F6cmuSUKyMz3os0iPBtYiLY+0GmASizeUDflSRGCfbU9MYFWY85XEBhID",
	"bCclMUlolsiyFGYGjIylsRyBNTFsM+BvAXl1j/81MXktY5W+Utfg/AjQTkpdQGequLKU1fTJKC6sTFX1",
	"T7BaxqVRKJSd3Yv9LxNC8a+aBmcHeaEwS7TmRE95wYVWK96Nhphb6dLIPATKKOFbeQZMeXbeWlcNXSvp",
	"lu3wIeaHoQjp9jEEOFPTsfvBkdh6JLZeCu9kZMpN/QgWuxMpfFqOYZAVTBILm6RdLQUY+oeXBAhvEsan",
	"Labw1msCaqJ4TWfc9/8qiuqjkYKik6aoj973R77o/vV7/wS4Srhw9852n5wfnchvDoTnyY7SC+F+CedD",
	"91B43sXms/ODr+S5qi3c9tnfv4UDlrzVG2LCmToRkfv1687sVcJD6HxIAZ8Qq07v6C/dzrMIPask7ORI",
	"opRV/+4zXfFZzEAmwcl9wE9xcsI08S9Cp0EQWJ44K+N260fTcvrN5ln761xyTKxIcgomUu/R8+72w6nk",
	"UhVPMZsG/4Jw3ckUItgZJ6VMPEyaahjZSTWCpUnkVRXfM4wpkVXF159YRSjKSC+fKLCG6Xq4r3WogSpI",
	"UW0dwW49eDZ5H/IxZJH3b9g+bH0svGPw4Ivj7jG8uffm/MXvH8bvGhhqlVPraWdISSnjoQ4kR/cjzzdg",
	"4pTxp99s9g7/HNwbgZwO/A7l8GDZ7U8Ojx4YZEXJGO6fIFLGx/uimePDtmhrpfXfAAAA///96xIybC4A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
