services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./server
          ignore:
            - tmp/
            - build-errors.log
        - action: rebuild
          path: ./client
          ignore:
            - node_modules/
            - dist/
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: main

  mariadb:
    image: mariadb:12.3.3@sha256:dd9b303aed4f4890ed09f766d8ca9ddfd176c0c6f6267feff53b3192ec65a979
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 1s
      timeout: 10s
      retries: 60

  openapi-ui:
    image: swaggerapi/swagger-ui:v5.32.11@sha256:e43eb34b978af58d8cb78e5da9c12d605cf43d113ad3a96b18f9b028d6479d68
    profiles:
      - docs
    ports:
      - "8100:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/docs/openapi.yaml:ro
