version: '3'

tasks:
  server-dev:
    cmd: docker compose up --build --watch app
    ignore_error: true
  server-dev-down:
    cmd: docker compose down
  openapi-ui:
    cmd: docker compose --profile docs up openapi-ui

  install-server-openapi-codegen:
    cmd: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.7.1
  server-openapi-codegen:
    cmd: oapi-codegen --config=./server/oapi-config.yaml docs/openapi.yaml
