name: Server

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
    paths:
      - server/**/*
      - schema/**/*
      - .github/workflows/server.yaml
  pull_request:
    paths:
      - server/**/*
      - schema/**/*
      - .github/workflows/server.yaml

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: './server/go.mod'
      - name: Format
        run: go fmt ./...
        working-directory: ./server/

  build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: './server/go.mod'
      - name: Build
        run: go build .
        working-directory: ./server/

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: './server/go.mod'
      - name: Test
        run: go test -v ./...
        working-directory: ./server/
